allprojects {
    group = 'com.riczan.choosedestin'
    version = '1.0.0'

    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
    }
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release.set(17)
    }
}
