minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
fabric_loader_version=0.15.11
fabric_api_version=0.92.0+1.20.1
forge_version=47.2.0
neoforge_version=20.4.237
quilt_loader_version=0.26.0
quilt_fabric_api_version=7.4.0+0.92.0-1.20.1

mod_id=choose_your_destin
mod_name=Choose Your Destin
mod_version=1.0.0
mod_author=riczan
